/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simuladordetomadedeciones;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class AgregarEmpleado extends javax.swing.JFrame {
           
       
        
    /**
     * Creates new form AgregarEmpleado
     */
    public AgregarEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        //.setFullScreenWindow(frame);
    }
    
    

    
     public void IngresarEmpleado(){
        Statement ps = null;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        String [] datos = new String[6];
        String sql4 = "select max(idEmpleados)  FROM empleados";
        String IdPruebaE;
        int NumeroIdE;
        String IdEmpleado;
        Statement st;
        try{
            st = conexion.createStatement();

             ResultSet rs = st.executeQuery(sql4);
             while(rs.next()){
                datos[3] = rs.getString(1);
                 System.out.println("Id Direccion = "+datos[3]);
            }
             
             if (datos[3]==null) {
               IdPruebaE = "0"; 

            }else{
              IdPruebaE = datos[3]; 

             }
            NumeroIdE = Integer.parseInt(IdPruebaE)+1;
            IdEmpleado = Integer.toString(NumeroIdE);

            
             
            String Nombre= NombreEmpleadoTxt.getText();
            String Apellidos = ApellidosTxt.getText();
            
            String NombreEmpleado = Nombre +" "+Apellidos;

            String Rfc = RcfTxt.getText();
     
            String IdDirrecion =  IngresarEmpleados.IdEmp;   
            
           
            System.out.println("Id Empleado: "+IdEmpleado);

            String sql = "INSERT INTO empleados  VALUES ("+IdEmpleado+", '"+NombreEmpleado+"', '"+Rfc+"')";
            ps = conexion.createStatement();
            
            System.out.println(sql);
            ps.execute(sql);
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreEmpleadoTxt = new javax.swing.JTextField();
        RcfTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ApellidosTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setSize(new java.awt.Dimension(503, 389));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Nombre Del Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel8.setText("RFC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        NombreEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpleadoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 147, -1));

        RcfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RcfTxtActionPerformed(evt);
            }
        });
        jPanel1.add(RcfTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 147, -1));

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        ApellidosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosTxtActionPerformed(evt);
            }
        });
        jPanel1.add(ApellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 147, -1));

        jLabel9.setText("Apellidos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 503, 389));

        setSize(new java.awt.Dimension(519, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RcfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RcfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RcfTxtActionPerformed

    private void NombreEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpleadoTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //this.setVisible(false);
       // VistaPrincipal in = new VistaPrincipal();
       // in.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres agregar a este nuevo empleado?:\n " , "Agregar empleado",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) {
             IngresarEmpleado();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ApellidosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosTxt;
    private javax.swing.JTextField NombreEmpleadoTxt;
    private javax.swing.JTextField RcfTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
