/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simuladordetomadedeciones;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */




public class AgregarRelacion extends javax.swing.JFrame {
    
    Connection conexion;
    boolean vacio = true;
    boolean primeravez1 =true, primeravez2=true;
    int emp1_id,emp2_id;
    String tipo_relacion;
    
    public AgregarRelacion() {
        initComponents();
        conexion =   conectar();
       // RCombo("empleados","NombreEmpleado",ComboB1,jtf_empleado1.getText());
        //RCombo("tiporelacion","NombreRelacion",ComboB2,jtf_empleado2.getText());
        //RCombo("empleados","NombreEmpleado",ComboB3);
        start_table("EMPLEADOS","",conexion);
        opciones_relacion();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combob_rel = new javax.swing.JComboBox<>();
        jb_agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtf_empleado1 = new javax.swing.JTextField();
        jtf_empleado2 = new javax.swing.JTextField();
        jb_buscar1 = new javax.swing.JButton();
        jb_buscar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jl_emp1 = new javax.swing.JLabel();
        jl_emp2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(566, 370));

        jPanel1.setMaximumSize(new java.awt.Dimension(566, 370));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 90, 30));

        jLabel1.setText("Buscar empleado por RFC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setText("Tipo De Relacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        combob_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combob_relActionPerformed(evt);
            }
        });
        jPanel1.add(combob_rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 140, 150, -1));

        jb_agregar.setText("Agregar");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 90, 33));

        jLabel3.setText("Buscar empleado por RFC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 190, -1));

        jtf_empleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtf_empleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_empleado1MouseClicked(evt);
            }
        });
        jtf_empleado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_empleado1KeyReleased(evt);
            }
        });
        jPanel1.add(jtf_empleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jtf_empleado2.setToolTipText("Buscar 2do Empleado ");
        jtf_empleado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_empleado2MouseClicked(evt);
            }
        });
        jtf_empleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_empleado2ActionPerformed(evt);
            }
        });
        jtf_empleado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_empleado2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_empleado2KeyReleased(evt);
            }
        });
        jPanel1.add(jtf_empleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 190, -1));

        jb_buscar1.setText("Buscar");
        jb_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jb_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 70, -1));

        jb_buscar2.setText("Buscar");
        jb_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jb_buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 70, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 130));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 330, 130));

        jl_emp1.setText("-");
        jPanel1.add(jl_emp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jl_emp2.setText("-");
        jPanel1.add(jl_emp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combob_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combob_relActionPerformed
         tipo_relacion = (String) combob_rel.getSelectedItem();
    }//GEN-LAST:event_combob_relActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres crear esta relacion?", "Relacion entre empleados",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) {
            if(es_vacio()== false){    
                IngresarRelacion(emp1_id,emp2_id,tipo_relacion);  
            }
        }
       
    }//GEN-LAST:event_jb_agregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtf_empleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_empleado2ActionPerformed
        
       // 
        //jtf_empleado2.setForeground(Color.PINK);
        
    }//GEN-LAST:event_jtf_empleado2ActionPerformed

    private void jtf_empleado2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empleado2KeyPressed
      // Color color_base = new Color(155,155,155);
       // 
    }//GEN-LAST:event_jtf_empleado2KeyPressed

    private void jtf_empleado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_empleado2MouseClicked
        
       
    }//GEN-LAST:event_jtf_empleado2MouseClicked

    private void jtf_empleado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_empleado1MouseClicked
        
    }//GEN-LAST:event_jtf_empleado1MouseClicked

    private void jtf_empleado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empleado1KeyReleased
       
    }//GEN-LAST:event_jtf_empleado1KeyReleased

    private void jtf_empleado2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empleado2KeyReleased
        
    }//GEN-LAST:event_jtf_empleado2KeyReleased

    private void jb_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar1ActionPerformed
        //int combo_1=  1;
        buscar(table1, jtf_empleado1.getText());
    }//GEN-LAST:event_jb_buscar1ActionPerformed

    private void jb_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar2ActionPerformed
       
        buscar(table2, jtf_empleado2.getText());
        
    }//GEN-LAST:event_jb_buscar2ActionPerformed

    private void table1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MousePressed
        //SE CREAN LAS VARIABLES PARA LAS COORDENADAS 
        int fila = table1.getSelectedRow(); 
        //  SE TOMA EL NOMBRE DEL USUARIO
        String text = table1.getValueAt(fila, 1).toString(); 
        jl_emp1.setText("Empleado seleccionado: "+text);
         // SE TOMA SU ID 
        text = table1.getValueAt(fila, 0).toString();
        emp1_id = Integer.parseInt(text);
        System.out.println("id seleccionado"+emp1_id );
    }//GEN-LAST:event_table1MousePressed

    private void table2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MousePressed
       int fila = table2.getSelectedRow(); 
       String text = table2.getValueAt(fila, 1).toString(); 
       jl_emp2.setText("Empleado seleccionado: "+text);
       
       text = table2.getValueAt(fila, 0).toString();
        emp2_id = Integer.parseInt(text);
        System.out.println("id_seleccionado"+emp2_id );
    }//GEN-LAST:event_table2MousePressed
//TABLA DE TIPO DE RELACIONES
    // IDTIPORELACION || NOMBRERELACION || VALORRELACION
    
    //TABLA DE RELACIONES
    // IDRELACION || TIPORELACION_IDTIPORELACION || EMPLEADOS_IDEMPLEADOS || EMPLEADOS_IDEMPLEADOS1

    
    
    public void IngresarRelacion(int p1,int  p2, String rel){
        // COMPROBAR IGUALDAD DE ID 
        if(p1== p2){
            JOptionPane.showMessageDialog(null,"Error. NO SE PUEDE RELACIONAR A UNA PERSONA CONSIGO MISMO. \n"); 
            return; 
        }
        System.out.println("persona 1:"+p1+"\tpersona 2:"+p2+"\trel: "+rel);
        Statement ps = null;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        Statement st;
        String [] datos = new String[6]; 
        String sql = "Select IDTIPORELACION from TIPORELACION where NOMBRERELACION = '"+rel+"'";
        int id_rel=0,id_max=0;
        //get id de la relacion
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id_rel = Integer.parseInt(rs.getString(1));
                System.out.println("ID DE RELACION : "+id_rel);
            }
        //COMPROBAR REPETICION DE REGISTRO
            String sql_dupli = "Select * from RELACION where TIPORELACION_IDTIPORELACION = "+id_rel+
                " AND EMPLEADOS_IDEMPLEADOS = "+p1+" AND EMPLEADOS_IDEMPLEADOS1 = "+p2;
            st = conexion.createStatement();
            rs = st.executeQuery(sql_dupli);
            System.out.println(sql_dupli);
            if (rs.next()) {
            // ResultSet is empty
                rs.close();
                st.close();
                JOptionPane.showMessageDialog(null,"Error. La relacion ya fue creada. \n");
                return;
            }     
        
        
        //AGREGAR
            //Conseguir valor ultimo de la tabla
        String sql2 = "SELECT max(IDRELACION) FROM RELACION";
            System.out.println(sql2);
        rs = st.executeQuery(sql2);
            while(rs.next()){
                
                System.out.println(rs.getString(1));
                
                if (rs.getString(1)==null) {
                    id_max=0;
                }else{
                  id_max = Integer.parseInt(rs.getString(1));

                }
                System.out.println("Id relacion from relacion mas grande: "+id_max);
            }
        //INSERTAR VALORES EN LA TABLA DE RELACIONES
        
          
 
       id_max=  id_max+1;
       
       
       String sql3 = "INSERT INTO RELACION  VALUES ("+id_max+", "+id_rel+", "+p1+","+p2+")";
       System.out.println("Insertar relacion: "+sql3);
       System.out.println(sql3);
       ps = conexion.createStatement(); 
       ps.execute(sql3);
       rs.close();
       st.close();
       ps.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error: NO EXISTE ESA RELACION  "+e.toString());
                    }  
    } 
    public void opciones_relacion(){
        String sql = "select NOMBRERELACION from TIPORELACION ";
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                combob_rel.addItem(rs.getString(1));
            } 
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    } 
    }
    
    public void buscar (JTable table, String textfield){
       // String sql = "select * from " + "empleados";
       textfield = textfield.toLowerCase();
        String sql = "SELECT * FROM EMPLEADOS where RFC like "+"'%"+textfield+"%"+"'";
        System.out.println(sql);
        //SELECT NOMBREEMPLEADO FROM APP.EMPLEADOS where NOMBREEMPLEADO like '%os%'
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idEmpleados");
        model.addColumn("NombreEmpleado");
        model.addColumn("rfc");
        table.setModel(model);
        
        Statement st;
        Conexion con = new Conexion();
        conexion = con.Conectar(); 
        String [] datos = new String[5];
        
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
           
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
               
                model.addRow(datos);
            }
        rs.close();
        st.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }  
    }
    
    public boolean es_vacio(){
    if(jl_emp1.getText().equals("-")){
        return true;
    }
    if(jl_emp2.getText().equals("-")){
        return true;
    }
    return false;
}
    
    public void start_table(String tabla,String RFC, Connection conexion2){
        String sql = "select * from " + tabla;
        
        Statement st; 
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idEmpleados");
        model.addColumn("NombreEmpleado");
        model.addColumn("RFC");
        
        table1.setModel(model);
        table2.setModel(model);
        
        String [] datos = new String[7];
        try{
            st = conexion2.createStatement();
            ResultSet rs;
          // if(RFC.equals("")){
               rs = st.executeQuery(sql); 
           //} else {
              // rs = st.executeQuery(sq2); 

           //}
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
               
                model.addRow(datos);
              
            }
            rs.close();
            st.close();
            
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }  
    }
    
    
    public  Connection conectar(){
        Conexion con = new Conexion();
        return conexion = con.Conectar();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRelacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combob_rel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_buscar1;
    private javax.swing.JButton jb_buscar2;
    private javax.swing.JLabel jl_emp1;
    private javax.swing.JLabel jl_emp2;
    private javax.swing.JTextField jtf_empleado1;
    private javax.swing.JTextField jtf_empleado2;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
