/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladordetomadedeciones;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Objects;

public class Asignar_nw_puesto extends javax.swing.JFrame {

    Connection conexion ;
    Boolean vacios_op = true, select_table1=false,select_table2=false, existente = false;
    Boolean tabla1 = true,tabla2=false;
    int emp1_id_table1, puesto_id_table2 ;
    String empleado_name_table1;
    String puesto_table2,rfc_table2,departamento_table2;
    int id_puesto_dupli = 0;
    
    
    public Asignar_nw_puesto() {
        initComponents();
        conexion =   conectar();
         
        mostrarEmpleados("EMPLEADOS","", conexion );
        mostrar_ocupados(conexion);
        jb_asignar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jb_asignar = new javax.swing.JButton();
        jlb_rfc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_buscaremp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jb_salir = new javax.swing.JButton();
        jl_emp_selec = new javax.swing.JLabel();
        jl_asig = new javax.swing.JLabel();
        jl_ins = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 450));
        setSize(new java.awt.Dimension(900, 450));

        jPanel1.setMaximumSize(new java.awt.Dimension(890, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 450));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_asignar.setText("Asignar");
        jb_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_asignarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_asignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        jlb_rfc.setText("Buscar personal por RFC");
        jPanel1.add(jlb_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        jLabel3.setText("2. Seleccione el puesto a reasignar de la lista");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 300, -1));

        jtf_buscaremp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_buscarempKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarempKeyReleased(evt);
            }
        });
        jPanel1.add(jtf_buscaremp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 250));

        jLabel1.setText("1. Seleccione un empleado para asignar un puesto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 500, 250));

        jb_salir.setText("Cancelar");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        jPanel1.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jl_emp_selec.setText("Empleado seleccionado: ");
        jPanel1.add(jl_emp_selec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jl_asig.setText("Puesto por asignar: ");
        jPanel1.add(jl_asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jl_ins.setText("-");
        jPanel1.add(jl_ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel5.setText("Seleccione un empleado de la lista");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_buscarempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarempKeyPressed
        
    }//GEN-LAST:event_jtf_buscarempKeyPressed

    private void jtf_buscarempKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarempKeyReleased
        // Buscar Empleado dentro de la BD
        String value_s = (String) jtf_buscaremp.getText(); 
        mostrarEmpleados("EMPLEADOS",value_s, conexion ); 
    }//GEN-LAST:event_jtf_buscarempKeyReleased

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jb_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_asignarActionPerformed
       int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres realizar esta asignación de puestos?:\n ", "Asignación de puestos",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) {
        //tomo el nombre del puesto de la tabla 2 que ha sido seleccionada
            
            //Se define si el nuevo puesto al que se va a asignar esta vacio
            if(vacios_op){
            //aqui se sabe que el puesto no tenia dueño anterior
                System.out.println("via 1 - el puesto no esta vacio");
            //si la persona ya tiene un puesto y se cambia por otro
                if (existente == true){
                    System.out.println("via 1.1 - el empleado ya tenia puesto");
                    //se reasigna al puesto nuevo del empleado
                    
                    //dejando el anterior vacio  
                    System.out.println("reasignar_existente");
                    reasignar_existente(emp1_id_table1);
                    
                    //Una vedejado vacio el puesto anterior
                    // se envia el id del puesto seleccionado
                    System.out.println("asignar vacio");
                    asignar_vacio(puesto_id_table2);
                    
                }else{
                    System.out.println("via 1.2 - el empleado no tenia puesto antes");
                    //si el empleado seleccionado no tenia puesto, entonces solo se asigna
                    // se envia el id del puesto seleccionado
                    System.out.println("asignar vacio");
                    asignar_vacio(puesto_id_table2);
                    
                }
            }else{
            //Si el nuevo puesto que se asignara ya estaba siendo ocupado
            //Se comprueba si la pesona ya tenia un puesto
                System.out.println("via 2 - el puesto esta vacio");
                if (existente == true){
                    System.out.println("via 2.1 - el empleado tiene puesto yo");
                    //si es asi, el puesto anterior se deja vacio
                    System.out.println("reasignar");
                    reasignar_existente(emp1_id_table1);
                    
                    
                    //y ahora el nuevo puesto se le cambia el empleado
                    System.out.println("reasignar");
                    reasignar(puesto_id_table2);
                    
                }else{ 
                    System.out.println("via 2.2 - el empleado no tenia puesto");
                    //Si el empleado que tendra el nuevo puesto no tiene puesto anterior
                    //se le asigna facilmente el nuevo puesto
                    System.out.println("reasignar");
                    reasignar(puesto_id_table2); 
                    
                } 
               
            } 
             
             mostrar_ocupados(conexion); 
             vacios_op=false;
             select_table2=false;
             existente = comprobar_existencia();
             boton_asig();
        }
         
       
        
    }//GEN-LAST:event_jb_asignarActionPerformed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
       //SE CREAN LAS VARIABLES PARA LAS COORDENADAS 
       select_table1 = true; 
       boton_asig();
        int fila = table.getSelectedRow(); 
        //  SE TOMA EL NOMBRE DEL USUARIO
        String text = table.getValueAt(fila, 1).toString();  
        empleado_name_table1 = text;
        System.out.println("Empleado seleccionado: "+text);
        jl_emp_selec.setText("Empleado seleccionado: "+text);
         // SE TOMA SU ID 
        text = table.getValueAt(fila, 0).toString();
        emp1_id_table1 = Integer.parseInt(text);
        System.out.println("id seleccionado: "+emp1_id_table1 ); 
        existente = comprobar_existencia();
        System.out.println("El empleado seleccionado ya tiene puesto:"+existente);
    }//GEN-LAST:event_tableMousePressed

    private void table2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MousePressed
        //Para comprobar su seleccion y no enviar algo vacio
        String text;
        select_table2 = true;
        boton_asig();
        int fila = table2.getSelectedRow(); 
        //  SE TOMA EL NOMBRE DEL empleado para ver si es la linea esta vacia
         
        Object value = table2.getValueAt(fila, 2);
        //Se comprueba que el puesto este vacio
        if (Objects.isNull(value)) {
            System.out.println("ESTA NULO");
            vacios_op=true;
        }else{
            vacios_op=false;
        }
        
        text = table2.getValueAt(fila, 1).toString(); 
        jl_asig.setText("Puesto por asignar: "+text);
         System.out.println("Puesto por asignar: "+text);
         
         // SE TOMA la ID del puesto nuevo
        text = table2.getValueAt(fila, 0).toString();
        puesto_id_table2  = Integer.parseInt(text);
        System.out.println("id seleccionado: "+puesto_id_table2 );
        
        //SU departamento
        departamento_table2 = table2.getValueAt(fila, 3).toString(); 
        System.out.println("departamento seleccionado: "+departamento_table2 );
        
    }//GEN-LAST:event_table2MousePressed
    

//comprobacion para activar o desactivar el boton de asignar
    public void boton_asig(){
        //si se han seleccionado filas en ambas tablas
        //se activa el boton
        if((select_table1 == true)&&(select_table2 == true)){
                jb_asignar.setEnabled(true);
        }else{
            //de lo contrario se mantiene desactivado
            jb_asignar.setEnabled(false);
        }
    }
    
    public void reasignar_existente(int id_oldpuesto){
      //marcar como vacio el puesto anterior de la persona 
        Statement st;
        // OBTENER EL ID DEL EMPLEADO seleccionado 
        try{
            st = conexion.createStatement(); 
            //se deja como nulo
            String sql2= "UPDATE PUESTO SET EMPLEADOIDPUESTO = null WHERE EMPLEADOIDPUESTO = "+emp1_id_table1;
            
            st.execute(sql2); 
            System.out.println(sql2);
            st.close(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        } 
    }
    
    
    
      public void reasignar(int idpuesto){
          //Se recibe el id del nuevo puesto
         //Metodo para cambiar el empleado de un puesto facilmente
        Statement st;
        // OBTENER EL ID DEL EMPLEADO seleccionado j
        int id_empleado = emp1_id_table1;  
        try{
            st = conexion.createStatement(); 
            String sql2= "UPDATE PUESTO SET EMPLEADOIDPUESTO = "+id_empleado+" WHERE IDPUESTO = "+puesto_id_table2;
            
            System.out.println(sql2);
            st.execute(sql2); 
            st.close(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
      }
    
    
    public boolean comprobar_existencia(){
        //query para comprobar coincidencias 
        //verificar si un empleado ya tiene un puesto asignado
        String sql = "SELECT EMPLEADOIDPUESTO from PUESTO where EMPLEADOIDPUESTO = "+emp1_id_table1;
        
        Statement st;
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql); 
            System.out.println(sql);
            if (!rs.next()) {
            // ResultSet esta vacio, y no hay coincidencias. 
            // No existe repeticion de registro
                rs.close();
                st.close();
                id_puesto_dupli = 0;
                 System.out.println("SE hizo la comprobacion y no hay existente");
                 //se retorna un falso denotando que no hay duplicados
                return false;
            }
            int count = rs.getInt(1);
            System.out.println("se hizo la comprobacion exitosa y hay un existene");
            rs.close();
            st.close();
            id_puesto_dupli = count;
            return true; 
            //Esta comparando si count es difernte a 0
            //si hay repeticiones, entonces manda un true
            //si no hay duplicados, entonces manda un false porque SI HAY 0 
        }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error. Hubo un problema durante la conexión del servidor. \n"+e.toString());
        } 
    
        return true;
    } 
    
    public void asignar_vacio(int id_nuevopuesto){
        //metodo para asignar a un empleado un puesto que esta vacio
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
         
        try{
            st = conexion.createStatement();
            
             //se asigna el puesto vacio al empleado usando su id
            String sql2= "UPDATE PUESTO SET EMPLEADOIDPUESTO = "+emp1_id_table1+" WHERE IDPUESTO = "+puesto_id_table2;
         
            st = conexion.createStatement();
            System.out.println(sql2);
            st.execute(sql2); 
            System.out.println(sql2);
            
            st.close(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }
    
    public void mostrar_ocupados(Connection conexion2){
        String sql = "SELECT PUESTO.IDPUESTO, PUESTO.NOMBREPUESTO, EMPLEADOS.NOMBREEMPLEADO, PUESTO.DEPARTAMENTO, EMPLEADOS.RFC" +
                     " FROM PUESTO " +
                     "LEFT OUTER JOIN EMPLEADOS ON EMPLEADOS.IDEMPLEADOS = PUESTO.EMPLEADOIDPUESTO ";
        Statement st; 
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("PUESTO");
        model.addColumn("Empleado");
        model.addColumn("DEPARTAMENTO");
        model.addColumn("RFC");
        table2.setModel(model);
        String [] datos = new String[7];
        try{
            st = conexion2.createStatement();
            ResultSet rs; 
            rs = st.executeQuery(sql); 
            
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3); 
                datos[3]= rs.getString(4);
                datos[4]= rs.getString(5);
                model.addRow(datos); 
            } 
            rs.close();
            st.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        } 
    }
     
     public void mostrarEmpleados(String tabla,String Persona, Connection conexion2){
        String sql = "select * from " + tabla;
        Persona = Persona.toLowerCase();
        String sq2 = "select * from " + tabla+" where lower(RFC) like"+" "+"'%"+Persona+"%"+"'";
        Statement st; 
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Empleado");
        model.addColumn("RFC");
        table.setModel(model);
       
        String [] datos = new String[7];
        try{
            st = conexion2.createStatement();
            ResultSet rs;
           if(Persona.equals("")){
               rs = st.executeQuery(sql); 
           } else {
               rs = st.executeQuery(sq2); 

           }
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3); 
                model.addRow(datos);
              
            } 
            rs.close();
            st.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }  
    }
     
    public  Connection conectar(){
        Conexion con = new Conexion();
        return conexion = con.Conectar();
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignar_nw_puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignar_nw_puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignar_nw_puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignar_nw_puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignar_nw_puesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_asignar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JLabel jl_asig;
    private javax.swing.JLabel jl_emp_selec;
    private javax.swing.JLabel jl_ins;
    private javax.swing.JLabel jlb_rfc;
    private javax.swing.JTextField jtf_buscaremp;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables

   
}
