/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simuladordetomadedeciones;

import Objetos.ItemCombo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class EditarRelacion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarRelacion
     */
    public EditarRelacion() {
        initComponents();
        
        RCombo("RELACIOCONID","NombreEmpleado",ComboB1);
    
    }
    
    
    public void RCombo(String tabla,String columna,JComboBox combob ){
                String sql = "select * from " + tabla;
                Statement st;
                Conexion con = new Conexion();
                Connection conexion = con.Conectar();
                int id;
                String Descripcion;
                try{
                    st = conexion.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                        id = Integer.parseInt(rs.getString(1));
                        Descripcion= rs.getString(2)+" --------- "+rs.getString(3)+" ----- "+"De "+rs.getString(4);
                        combob.addItem(new ItemCombo (id,Descripcion)); 
            }  
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    } 
    }
    
    public void RCombo_text(String tabla,String columna,JComboBox combob, String like ){
        like = like.toLowerCase();
        String sql = "select * from " + tabla+" where lower(NOMBREEMPLEADO) like '%"+like+"%'";
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        int id;
        String Descripcion;
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ComboB1.removeAllItems();
            while(rs.next()){
                id = Integer.parseInt(rs.getString(1));
                Descripcion= rs.getString(2)+" --------- "+rs.getString(3)+" ----- "+"De "+rs.getString(4);
                combob.addItem(new ItemCombo (id,Descripcion)); 
            }  
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    } 
    }
    
    
    
    public void EliminarRelacion(int idRelacion){
        String sql1 = "DELETE FROM RELACION WHERE IDRELACION = "+idRelacion;
        Conexion con = new Conexion();
        Statement ps = null;
        Connection conexion = con.Conectar();
        try {
            ps = conexion.createStatement();
            System.out.println(sql1);
            ps.execute(sql1);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboB1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Relacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        ComboB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboB1ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 356, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 86, 33));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 90, 33));

        jtf_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_buscarActionPerformed(evt);
            }
        });
        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyReleased(evt);
            }
        });
        jPanel1.add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 120, -1));

        jLabel2.setText("Nombre del primer empleado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres eliminar esta relación?:\n", "Eliminar relación entre empleados",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) {
        ItemCombo item = (ItemCombo)ComboB1.getSelectedItem();
        System.out.println(item.getId());
        EliminarRelacion(item.getId());
         ComboB1.setSelectedIndex(-1);
          
             RCombo("RELACIOCONID","NombreEmpleado",ComboB1);
        }
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboB1ActionPerformed

    private void jtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyReleased
        // TODO add your handling code here:
        ComboB1.setSelectedIndex(-1);
        ComboB1.removeAllItems();
        RCombo_text("RELACIOCONID","NombreEmpleado",ComboB1,jtf_buscar.getText());
    }//GEN-LAST:event_jtf_buscarKeyReleased

    private void jtf_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarRelacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboB1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_buscar;
    // End of variables declaration//GEN-END:variables
}
