/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simuladordetomadedeciones;

import Objetos.ItemCombo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Eliminar_usuario extends javax.swing.JFrame {

    /** Creates new form Eliminar_usuario */
    public Eliminar_usuario() {
        initComponents();
        RCombo("USUARIOS",jcb_usuarios, "");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_salir = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jcb_usuarios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        jPanel2.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel1.setText("Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setText("Buscar usuario por RFC");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyReleased(evt);
            }
        });
        jPanel2.add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        jPanel2.add(jcb_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyReleased
        // 
         RCombo("USUARIOS",jcb_usuarios, jtf_buscar.getText());
    }//GEN-LAST:event_jtf_buscarKeyReleased

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
       // Cuando se quiera eliminar
        //se toma el objeto del item seleccionado
        ItemCombo item = (ItemCombo)jcb_usuarios.getSelectedItem();
        System.out.println(item.getId());
        
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres eliminar este usuario?:\n"+item.toString(), "Eliminar usuario",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) { 
            EliminarEmpleado(item.getId());  
            RCombo("USUARIOS",jcb_usuarios, "");
        }
        
        
        
        
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed
     
    public void EliminarEmpleado(int idEmpleado){
        String sql1 = "DELETE FROM USUARIOS WHERE IDUSUARIO = "+idEmpleado;
        Conexion con = new Conexion();
        Statement ps = null;
        Connection conexion = con.Conectar();
        try {
            ps = conexion.createStatement();
            System.out.println(sql1);

            ps.execute(sql1);
        } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
     }
    
    public void RCombo(String tabla,JComboBox combob, String empleado){
                String sql = "select * from " + tabla+ " where RFCUSUARIO like '%"+empleado+"%'";
                Statement st;
                Conexion con = new Conexion();
                Connection conexion = con.Conectar();
                int id;
                String Descripcion;
                //reinicia el contenido de los items para no repetir
                combob.removeAllItems();
                try{
                    st = conexion.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    //SE RECORREN LAS FILAS DE LOS DATOS OBTENIDOS
                    while(rs.next()){
                    // SE OBTIENE SU ID
                     id = Integer.parseInt(rs.getString(1));
                     //
                    Descripcion= rs.getString(2);
                    //se guarda el id del usuario dentro de un objeto item
                combob.addItem(new ItemCombo (id,Descripcion));
            } 
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<String> jcb_usuarios;
    private javax.swing.JTextField jtf_buscar;
    // End of variables declaration//GEN-END:variables

}
