/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladordetomadedeciones;

import Objetos.ItemCombo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Eliminar_tipo_relacion extends javax.swing.JFrame {

    Connection conexion;
    int id_rel;
    public Eliminar_tipo_relacion() {
        initComponents();
        conexion = conectar();
        
        opciones_relacion_inicio();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_eliminar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jcb_rel = new javax.swing.JComboBox<>();
        jtf_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(460, 193));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        jPanel1.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 65, -1));

        jcb_rel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_relMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcb_relMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcb_relMouseReleased(evt);
            }
        });
        jcb_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_relActionPerformed(evt);
            }
        });
        jPanel1.add(jcb_rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 51, 160, -1));

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyReleased(evt);
            }
        });
        jPanel1.add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 140, -1));

        jLabel1.setText("Buscar tipo de relación por su nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, -1));

        jLabel2.setText("Tipos de relación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_relActionPerformed
         
                
    }//GEN-LAST:event_jcb_relActionPerformed

    private void jtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyReleased
        jcb_rel.setSelectedIndex(-1);
        jcb_rel.removeAllItems();
        RCombo_text("TIPORELACION" ,jcb_rel,jtf_buscar.getText());
    }//GEN-LAST:event_jtf_buscarKeyReleased

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
      String tipo_relacion = (String) jcb_rel.getSelectedItem();
      int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres eliminar este tipo de relación?:\n "+tipo_relacion, "Tipo de relación",
        JOptionPane.YES_NO_OPTION); 
        if (confirmed == JOptionPane.YES_OPTION) {
             EliminarRelacion(tipo_relacion);
             jcb_rel.setSelectedIndex(-1);
            jcb_rel.removeAllItems();
            opciones_relacion_inicio();
        }
      
         
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jcb_relMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_relMouseClicked
         
    }//GEN-LAST:event_jcb_relMouseClicked

    private void jcb_relMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_relMouseReleased
 
    }//GEN-LAST:event_jcb_relMouseReleased

    private void jcb_relMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_relMousePressed
        
    }//GEN-LAST:event_jcb_relMousePressed
    public void EliminarRelacion(String Relacion){
        String sql1 = "DELETE FROM TIPORELACION WHERE NOMBRERELACION = '"+Relacion+"'";
        Conexion con = new Conexion();
        Statement ps = null;
        Connection conexion = con.Conectar();
        try {
            ps = conexion.createStatement();
            System.out.println(sql1);
            ps.execute(sql1);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }
    
    
    public void RCombo_text(String tabla ,JComboBox combob, String like ){
        like = like.toLowerCase();
        String sql = "select * from " + tabla+" where lower(NOMBRERELACION) like '%"+like+"%'";
        Statement st;
        Conexion con = new Conexion();
        conexion = con.Conectar(); 
        String Descripcion;
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jcb_rel.removeAllItems();
            while(rs.next()){ 
                Descripcion= rs.getString(2); 
                jcb_rel.addItem(Descripcion); 
            }  
            rs.close();
            st.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    } 
    }
    
    
    public void opciones_relacion_inicio(){
        String sql = "select * from TIPORELACION ";
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               // jcb_rel.addItem(rs.getString(1)); ID
               jcb_rel.addItem(rs.getString(2)); //Nombre
            }
            rs.close();
            st.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    } 
    }
    
    
    
    public  Connection conectar(){
        Conexion con = new Conexion();
        return conexion = con.Conectar();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_tipo_relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_tipo_relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_tipo_relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_tipo_relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_tipo_relacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<String> jcb_rel;
    private javax.swing.JTextField jtf_buscar;
    // End of variables declaration//GEN-END:variables
}
