/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladordetomadedeciones;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ModificarEmpleado extends javax.swing.JFrame {

  Connection conexion ;
  Boolean existe= false,seleccionado = false;
  
    
    public ModificarEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
         conexion =   conectar();
         Es_vacio();
        mostrarEmpleados("empleados","", conexion );
        
         
        //this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
    }
    
    public  Connection conectar(){
        Conexion con = new Conexion();
        return conexion = con.Conectar();
    }
    
    public void mostrarEmpleados(String tabla,String Persona, Connection conexion2){
        String sql = "select * from " + tabla;
        Persona = Persona.toLowerCase();
        String sq2 = "select * from " + tabla+" where lower(NombreEmpleado) like"+" "+"'"+Persona+"%"+"'";
        Statement st;
      // Conexion con = new Conexion();
       // conexion2 = con.Conectar();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idEmpleados");
        model.addColumn("NombreEmpleado");
        model.addColumn("rfc");
        visor2.setModel(model);
       
        String [] datos = new String[7];
        try{
            st = conexion2.createStatement();
            ResultSet rs;
           if(Persona.equals("")){
               rs = st.executeQuery(sql); 
           } else {
               rs = st.executeQuery(sq2); 

           }
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
               
                model.addRow(datos);
              
            } 
            rs.close();
            st.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }  
    }
    
    public String col_INT (String col,String textfield){
       if ((col == "rfc") || (col == "idempleados")){
           return  "select * from empleados where "+ col +" = "+textfield;
                    
       }        //SELECT * FROM MyTable WHERE CAST(Team_Mobile AS NVARCHAR(MAX)) LIKE @Team_Mobile + '%'
       else{
           return  "select * from empleados where lower("+ col +") like"+" "+"'"+textfield+"%"+"'";
       }
    }
    
    public void buscar (String col,String textfield){
        String sql = "select * from " + "empleados";
        textfield = textfield.toLowerCase();
      String sql2 = col_INT(col,textfield);
        
         
        Statement st;
        Conexion con = new Conexion();
        conexion = con.Conectar();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idEmpleados");
        model.addColumn("NombreEmpleado");
        model.addColumn("RFC");
        visor2.setModel(model);
       
        String [] datos = new String[7];
        try{
            st = conexion.createStatement();
            ResultSet rs;
           if(textfield.equals("")){
               System.out.println(sql);
               rs = st.executeQuery(sql); 
           } else {
               System.out.println(sql2);
               rs = st.executeQuery(sql2); 

           }
            while(rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
               
                model.addRow(datos);
              
            } 
            
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }  
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor2 = new javax.swing.JTable();
        jB_aplicarCambios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();
        jTF_rfc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jL_ID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCB_camposBuscar = new javax.swing.JComboBox<>();
        jB_buscar = new javax.swing.JButton();
        jTF_search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jB_elimina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visor2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        visor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visor2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(visor2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 210));

        jB_aplicarCambios.setText("Modificar");
        jB_aplicarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_aplicarCambiosActionPerformed(evt);
            }
        });
        jPanel1.add(jB_aplicarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel1.setText("Nombre del Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 150, 20));

        jLabel3.setText("RFC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 30, 20));
        jPanel1.add(jTF_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 150, -1));
        jPanel1.add(jTF_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 150, -1));

        jLabel4.setText("id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jL_ID.setText("[ ]");
        jPanel1.add(jL_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 140, -1));

        jLabel6.setText("Buscar por:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 80, -1));

        jCB_camposBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de Empleado", "RFC", "ID de Registro" }));
        jCB_camposBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_camposBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_camposBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 190, -1));

        jB_buscar.setText("Buscar");
        jB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(jB_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 70, 20));
        jPanel1.add(jTF_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 190, -1));

        jLabel7.setText("Ingrese el dato:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, -1));

        jB_elimina.setText("Eliminar");
        jB_elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_eliminaActionPerformed(evt);
            }
        });
        jPanel1.add(jB_elimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visor2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visor2MousePressed
        jB_elimina.setEnabled(true);
         jB_aplicarCambios.setEnabled(true);
        int fila = visor2.getSelectedRow(); 
            
        if(fila>=0){
           jL_ID.setText(visor2.getValueAt(fila, 0).toString());
           jTF_nombre.setText(visor2.getValueAt(fila, 1).toString()); 
            jTF_rfc.setText(visor2.getValueAt(fila, 2).toString()); 
        }else{
           // JOptionPane.showMessageDialog(null,"No selecciono fila");
        } 
    }//GEN-LAST:event_visor2MousePressed

    private void jCB_camposBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_camposBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_camposBuscarActionPerformed

    private void jB_eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_eliminaActionPerformed
        
         int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres eliminar este registro?", "Eliminación de Registros",
        JOptionPane.YES_NO_OPTION);
     if (confirmed == JOptionPane.YES_OPTION) {
      Borrar_registro();
    }
     mostrarEmpleados("empleados","", conexion );
    }//GEN-LAST:event_jB_eliminaActionPerformed

    private void jB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarActionPerformed
         String columna = item_selected();
         // public void buscar (String col,String textfield){
         String value_Search = (String) jTF_search.getText();
         buscar(columna, value_Search);
         
    }//GEN-LAST:event_jB_buscarActionPerformed

    private void jB_aplicarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_aplicarCambiosActionPerformed
     int confirmed = JOptionPane.showConfirmDialog(null, 
        "¿Estas seguro de que quieres modificar este registro?", "Modificación de Registros",
        JOptionPane.YES_NO_OPTION);
     if (confirmed == JOptionPane.YES_OPTION) {
      Modificar(jL_ID.getText());
    }
      mostrarEmpleados("empleados","", conexion );
    }//GEN-LAST:event_jB_aplicarCambiosActionPerformed
//JOptionPane.showMessageDialog(null,"No se encontro registro alguno");
    public void Modificar(String np){

        Statement ps = null;
        String sql = "update empleados set nombreempleado= '"+
                jTF_nombre.getText().toString()+"', rfc = '"+
                jTF_rfc.getText().toString()+"'  where idempleados = "+np+"";
        System.out.println(sql);
        Conexion con = new Conexion();
        Connection conexion = con.Conectar();
        try{
            ps = conexion.createStatement();
            System.out.println(sql);
            ps.execute(sql);
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error"+e.toString());
                    }

         
    }
        /*
    https://db.apache.org/derby/docs/10.0/manuals/reference/sqlj52.html
    */
       
    public void Borrar_registro(){
        
           // String idEmpleado = jL_ID.getText();
            String sql1 = "DELETE FROM EMPLEADOS WHERE rfc = "+ "'"+jTF_rfc.getText().toString()+"'"+"";
            Conexion con = new Conexion();
            Statement ps = null;
            Connection conexion = con.Conectar();

            try {
                ps = conexion.createStatement();
                System.out.println(sql1);
                ps.execute(sql1);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null,"Ese registro no existe"+e.toString());
                }
        
    }
    public String item_selected (){
        String select = jCB_camposBuscar.getSelectedItem().toString();
    
         if (select == "Nombre de Empleado"){
            return "nombreempleado";
         }
        else if (select == "RFC"){
            return "rfc";
         }
        else{
            return "idempleados";
        }
    }
    
 public void Es_vacio() {
     if (seleccionado == false){
         jB_elimina.setEnabled(false);
         jB_aplicarCambios.setEnabled(false);
     }
     
 }    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEmpleado().setVisible(true);
                //ModificarEmpleado n = new ModificarEmpleado();
               // n.mostrarEmpleados("empleados","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_aplicarCambios;
    private javax.swing.JButton jB_buscar;
    private javax.swing.JButton jB_elimina;
    private javax.swing.JComboBox<String> jCB_camposBuscar;
    private javax.swing.JLabel jL_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_rfc;
    private javax.swing.JTextField jTF_search;
    private javax.swing.JTable visor2;
    // End of variables declaration//GEN-END:variables

   

}
