/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.Path2D;
import javax.swing.Icon;

/**
 *
 * @author oscar
 */
public class PanelCargando extends javax.swing.JPanel {
    
    private boolean deslizarModo;
    private float animate;
    /**
     * Creates new form PanelCargando
     */
    public PanelCargando() {
        initComponents();
        //setOpaque(false);
        
    }
    
    public void colarAnimacion(boolean deslizarModo, float animate){
        this.deslizarModo=deslizarModo;
        this.animate=animate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boton2 = new simuladordetomadedeciones.Boton();
        boton1 = new simuladordetomadedeciones.Boton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladordetoma/Imagenes/administrador.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 247));

        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setText("Iniciar");
        boton2.setFocusable(false);
        boton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 109, 41));

        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setText("Regresar");
        boton1.setFocusable(false);
        boton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 109, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
      public void eventobotonRegresar(ActionListener event) {
        boton1.addActionListener(event);
    }
      
      
       public void eventobotoniniciar(ActionListener event) {
        boton2.addActionListener(event);
    }
       
       public void cambiarTextoLabel(String texto) {
   jLabel1.setText(texto);
        }
       
       public void cambiarTextoLabel2(String texto) {
   jLabel3.setText(texto);
        }
       
        public void cambiarImagen(Icon icon) {
        jLabel2.setIcon(icon);
        }
    
    
    public void paint(Graphics grphcs){
              Graphics2D g2=(Graphics2D)grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        int ancho = getWidth();
        int alto= getHeight();
        int x= 0;
        int y= 0;
            if (deslizarModo) {
                 int centrarY=alto/2;
        Path2D.Float p = new Path2D.Float();
        p.moveTo(x, y);
        p.lineTo(ancho, y);
        p.lineTo(ancho, alto);
        p.lineTo(x, alto);
        p.curveTo(x, alto, easeOutBounce(animate)*ancho, centrarY, x, y);
        g2.fill(p);
        
            } else {
                g2.fillRect(x, y, ancho, alto);
            }
        g2.dispose();
        super.paint(grphcs);
        
        
    }
      
         private float easeOutBounce(float x) {
float n1 = 7.5625f;
float d1 = 2.75f;
double v;
if (x < 1 / d1) {
    v = n1 * x * x;
} else if (x < 2 / d1) {
    v = n1 * (x -= 1.5 / d1) * x + 0.75;
} else if (x < 2.5 / d1) {
    v = n1 * (x -= 2.25 / d1) * x + 0.9375;
} else {
    v = n1 * (x -= 2.625 / d1) * x + 0.984375;
}

        if (deslizarModo) {
            return (float)(1f-v);
        }else{
            return (float)v;
        }
            
}
         
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private simuladordetomadedeciones.Boton boton1;
    private simuladordetomadedeciones.Boton boton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
